service: sls

frameworkVersion: '2'

custom:
  settings:
    BPI_TABLE: BTCPriceIndex

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - cloudformation:DescribeStackResource
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.BPI_TABLE}"

functions:
  putCryptoCurrency:
    handler: src/handlers/putCryptoCurrency.handler
    events:
      - schedule:
          rate: rate(10 minutes)
  getCurrencies:
    handler: src/handlers/getCurrencies.handler
    events:
      - http:
          path: /currencies
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
            scopes:
              - openid
          integration: lambda

resources:
  Resources: ${file(./CloudFormation.yml):Resources}
